### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.kde.PlatformTheme.QtSNI#1]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by ilya-fedin** [comment]
This project is discontinued

**Comment by hfiguiere** [comment]
It hasn't been EOLed so there is no way to know.

**Comment by ilya-fedin** [comment]
I have no idea how to EOL... There seem to be no way to archive this repo

**Comment by hfiguiere** [comment]
It's in the fine manual

https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life

archive comes after (ie the maintainers will do it on request AFTER the EOL)

**Comment by ilya-fedin** [comment]
thx, I did it
